# Scans dependency manifest changes in PRs for known vulnerabilities.
# Blocks merge on any dependency with moderate-or-higher severity CVEs.
# License denylist covers licenses incompatible with this project's Apache-2.0.
#
# Docs: https://github.com/actions/dependency-review-action
name: Dependency review

on:
  pull_request:
    branches: ['main']

permissions:
  contents: read
  pull-requests: write  # required for comment-summary-in-pr

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/dependency-review-action@v4
        with:
          comment-summary-in-pr: always
          fail-on-severity: moderate
          deny-licenses: >-
            GPL-1.0-or-later,
            LGPL-2.0-or-later,
            AGPL-1.0-or-later,
            SSPL-1.0,
            Commons-Clause
          retry-on-snapshot-warnings: true
